import pytest
from fetcher.transform import flatten_pr

def test_flatten_pr_ci_tagging():
    raw_pr = {
        "number": 101,
        "title": "Update CI",
        "body": "Fix workflows",
        "author": {"login": "dev-user"},
        "createdAt": "2024-05-01T10:00:00Z",
        "mergedAt": "2024-05-01T11:00:00Z",
        "additions": 10,
        "deletions": 2,
        "files": {
            "nodes": [
                {"path": "src/main.py", "additions": 5, "deletions": 1, "changeType": "MODIFIED"},
                {"path": ".github/workflows/deploy.yml", "additions": 5, "deletions": 1, "changeType": "ADDED"}
            ]
        },
        "reviewThreads": {"nodes": []},
        "commits": {"nodes": []},
        "reviews": {"nodes": []}
    }
    
    flattened = flatten_pr(raw_pr)
    assert flattened["touches_ci"] is True
    assert flattened["author_is_bot"] is False

def test_flatten_pr_bot_detection():
    raw_pr = {
        "number": 102,
        "title": "Bump version",
        "body": "Autogenerated",
        "author": {"login": "dependabot[bot]"},
        "createdAt": "2024-05-01T10:00:00Z",
        "mergedAt": "2024-05-01T11:00:00Z",
        "additions": 1,
        "deletions": 1,
        "files": {"nodes": [{"path": "package.json", "additions": 1, "deletions": 1, "changeType": "MODIFIED"}]},
        "reviewThreads": {
            "nodes": [
                {
                    "isResolved": True,
                    "path": "package.json",
                    "line": 10,
                    "comments": {
                        "nodes": [
                            {"author": {"login": "github-actions-bot"}, "body": "LGTM", "createdAt": "2024-05-01T10:30:00Z", "diffHunk": "@@ -10,1 +10,1 @@"}
                        ]
                    }
                }
            ]
        },
        "commits": {"nodes": []},
        "reviews": {"nodes": []}
    }
    
    flattened = flatten_pr(raw_pr)
    assert flattened["author_is_bot"] is True
    assert flattened["review_comments"][0]["is_bot"] is True
    assert flattened["touches_ci"] is False
